---
title: "Calculating_distance"
author: "Aoi Ogawa"
date: "2/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
# importing libraries
#library(datasets)
library(maps)
library(tidyr)
library(tidyverse)
library(readr)
library(geosphere)
library(sp)
library(leaflet)
library(magrittr)
library(janitor)
```

Before knit this document, run code in dataframes.R 

```{r, include=FALSE}
# importing data
games<-read.csv("data/games_Smith.csv")
#pbp<-read.csv("data/pbp_Smith.csv")
stadium_data_coordinates <- read.csv("stadium_data_coordinates.csv")
visit_team_data <- read.csv("visit_team_data.csv")
#ns_data_coordinates <- read.csv("Ns_data_coordinates.csv")
#all_data_coordinates <- read.csv("All_data_coordinates.csv")
```


```{r}
#cleaning df column names to have a common variable with games (home_team)
stadium_data_coordinates <- stadium_data_coordinates %>% 
  clean_names()

# games_w_coordinates = games + stadium_data_coordinates 
games_w_coordinates <- games %>%
  inner_join(stadium_data_coordinates)

# games_w_coordinates = games + stadium_data_coordinates + visit_team_data  
games_w_coordinates <- visit_team_data %>%
  clean_names() %>% 
  inner_join(games_w_coordinates)  

# clean games_w_coordinates 
games_w_coordinates <- games_w_coordinates %>%
  mutate(num = NULL) %>%
  rename(home_lat = longitude,
         home_long = latitude) 
  #distinct(game_key, .keep_all = TRUE)
```

```{r}
# create domestic games df 
domestic_games <- games_w_coordinates %>%
  filter(
    stadium != c(
      'Wembley Stadium',
      "Rogers Centre",
      "Wembley",
      "Twickenham",
      "Estadio Azteca",
      "Twickenham Stadium",
      "Azteca Stadium",
      "Tottenham Hotspur Stadium",
      "Tottenham Hotspur"
    )
  )
# create international games df 
#international_games <- games_w_coordinates %>% 
#  filter(
#    stadium == c(
#      'Wembley Stadium',
#      "Rogers Centre",
#      "Wembley",
#      "Twickenham",
#      "Estadio Azteca",
#      "Twickenham Stadium",
#      "Azteca Stadium",
#      "Tottenham Hotspur Stadium",
#      "Tottenham Hotspur"
#    )
#  )
```

```{r}
# calculate distance
calc_domestic <- domestic_games %>% 
  rowwise() %>%
  mutate(distance_m = distCosine(c(home_long, home_lat),c(visit_long, visit_lat)),
         distance_mile = distance_m*0.6214/1000)

# categorize distances 
calc_domestic <- calc_domestic %>%
  mutate(
    distance =
      case_when(
        distance_mile > 2000 ~ "very far",
        distance_mile > 1000 ~ "far",
        distance_mile <= 1000 ~ "close"
      ),
    color_dis =
      case_when(
        distance == "very far" ~ "red",
        distance == "far" ~ "orange",
        distance == "close" ~ "cyan"
      ),
    is_thurs =
      ifelse(game_day == "Thursday", 1, 0),
    stroke =
      ifelse(is_thurs == '1', "8", "NULL")
  )
```

```{r}
# Determines total distance each team traveled a given year 
total_dis<-function(year){
  
sum_distance <- calc_domestic %>%
  group_by(visit_team, season) %>%
  summarise(num =sum(distance_mile)) %>%
  filter(season == year)

  return(sum_distance)
}

# total distance traveld per season

# distance_2007_sum <- total_dis("2007")
# distance_2008_sum <- total_dis("2008") 
# distance_2009_sum <- total_dis("2009")
# distance_2010_sum <- total_dis("2010")
# distance_2011_sum <- total_dis("2011")
# distance_2012_sum <- total_dis("2012")
# distance_2013_sum <- total_dis("2013")
# distance_2014_sum <- total_dis("2014")
# distance_2015_sum <- total_dis("2015")
# distance_2016_sum <- total_dis("2016")
# distance_2017_sum <- total_dis("2017")
# distance_2018_sum <- total_dis("2018")
```


## Getting total distance for each team from 2007-2018
```{r}
sum_distance_season <- calc_domestic %>%
  group_by(visit_team, season) %>%
  summarise(travel_dis =sum(distance_mile))  %>%
  rename(team = visit_team)

num_games_season_visit <- calc_domestic %>%
  group_by(visit_team, season) %>%
  summarise(num_game_visit =n()) %>%
  rename(team = visit_team)

# function to get sem
se <- function(x) sqrt(var(x)/length(x))

# get sem
games_season_sem <- calc_domestic %>%
  group_by(visit_team, season) %>%
  summarise(sem=se(distance_mile)) %>%
  rename(team= visit_team)

num_games_season_home <- calc_domestic %>%
  group_by(home_team, season) %>%
  summarise(num_game_home =n()) %>%
  rename(team = home_team)

distance_season <- sum_distance_season %>%
  inner_join(num_games_season_visit) %>%
  inner_join(num_games_season_home)%>%
  mutate(total_game = num_game_visit + num_game_home) %>%
  inner_join(games_season_sem) %>%
  mutate(avg_travel = travel_dis/total_game)


sum_distance_all <- calc_domestic %>%
  group_by(visit_team) %>%
  summarise(travel_dis =sum(distance_mile)) %>%
  rename(team = visit_team)


num_games_visit <- calc_domestic %>%
  group_by(visit_team) %>%
  summarise(num_game_visit =n()) %>%
  rename(team = visit_team)

num_games_home <- calc_domestic %>%
  group_by(home_team) %>%
  summarise(num_game_home =n()) %>%
  rename(team = home_team)

# get the standard error mean for travel distance
all_games_sem <- calc_domestic %>%
  group_by(visit_team) %>%
  summarise(sem = se(distance_mile)) 


distance_all <- sum_distance_all %>%
  inner_join(num_games_visit) %>%
  left_join(num_games_home)%>%
  mutate(total_game = num_game_visit + num_game_home) %>%
  mutate(avg_travel = travel_dis/total_game)

# max(distance_all$avg_travel)-min(distance_all$avg_travel)
```


```{r}
# making the plot 
ggplot(distance_all, aes(x=team, y=avg_travel)) +
  geom_bar(stat="identity") + 
  coord_flip() + 
  labs(y = "Average Travel Distance from 2007 to 2018 (miles)", title = "Each Teams's Average Travel Distance")
  
```

```{r}
# facet wrap by season
# making the plot --> need a way to look at the each team names
ggplot(distance_season, aes(x=team, y=avg_travel)) +
  geom_bar(stat="identity") + 
  coord_flip() + 
  labs(y = "Average Travel Distance from 2007 to 2018 (miles)") +
  facet_wrap(vars(season))
```


```{r}
#some analysis
# without_season_dis <- calc_domestic %>%
#   group_by(Home_Team,Visit_Team,distance_mile) %>%
#   summarise(num=n())
# 
# season_dis <- calc_domestic %>%
#   group_by(Home_Team,Visit_Team,distance_mile,Season) %>%
#   summarise(num=n())
# 
# season_num_games_home <- calc_domestic %>%
#   group_by(Home_Team,Season) %>%
#   summarise(host_num=n())
# 
# season_num_games_visit <- calc_domestic %>%
#   group_by(Visit_Team,Season) %>%
#   summarise(visit_num=n())

```


```{r}
#WITHOUT ELO RANKINGS
mapping_travel <- function(Season, Team) {
  mapping_team <- calc_domestic %>%
    filter(season == Season,
           visit_team == Team) 
   
  travel_map <- mapping_team %>%
    leaflet() %>%
    addProviderTiles(providers$CartoDB.Positron) %>%
    setView(-93.65, 42.0285, zoom = 4.3) %>%
    addMarkers( ~ visit_long, ~ visit_lat) %>%
    addMarkers( ~ home_long, ~ home_lat) %>%
    addMarkers(
      lng = mapping_team$visit_long,
      lat = mapping_team$visit_lat,
      label = mapping_team$visit_team,
      labelOptions = labelOptions(noHide = T))
  
  for (i in 1:nrow(mapping_team)) {
    travel_map <- travel_map %>%
      addPolylines(
        lat = c(mapping_team[i, ]$visit_lat,
                mapping_team[i, ]$home_lat),
        lng = c(mapping_team[i, ]$visit_long,
                mapping_team[i, ]$home_long),
        color = mapping_team[i, ]$color_dis,
        dashArray = mapping_team[i,]$stroke
      ) %>%
      addMarkers(
        lng = mapping_team[i, ]$home_long,
        lat = mapping_team[i, ]$home_lat,
        label = mapping_team[i, ]$home_team,
        labelOptions = labelOptions(noHide = T)
      )
      # addMarkers(
      #   lng = mapping_team[i, ]$home_long,
      #   lat = mapping_team[i, ]$home_lat,
      #   popup = paste(
      #     mapping_team[i, ]$home_team,
      #     "<br>",
      #     mapping_team[i, ]$visit_team,
      #     "Ranking:",
      #     #round(mapping_team[i, ]$elo2_pre, digits = 0),
      #     #"<br>",
      #     #mapping_team[i, ]$home_team,
      #     #"Ranking:",
      #     #round(mapping_team[i, ]$elo1_pre, digits = 0),
      #     #"<br>"
      #   ),
      #   options = popupOptions(closeButton = TRUE)
      # )
  }
  
  return(travel_map)
  
}

mapping_travel("2016", "Los Angeles Rams")

```


```{r}
# run a permutation test

mean(distance_all$avg_travel)
# overall mean is 485.956

permutation_dis <- distance_all%>%
  mutate(over_mean = ifelse(avg_travel > mean(avg_travel), 'more_travel', 'less_travel')) 

mean_diff_travel<- permutation_dis%>%
  group_by(over_mean)%>%
  summarise(Mean = mean(avg_travel))

mean_diff_travel

# differences between the two means
666.9743-387.2188

permutation_dis %>% 
  group_by(over_mean) %>%
  summarise(num_team = n())

choose(34,12)

# regrouping = 548354040
```

### Adding Elo Rankings to Map 

```{r}
#cleaning data used in function including dataframe full_with_elo
full_with_elo <- full_with_elo %>%
  clean_names()

#joining datafram with distances and dataframe with elo rankings
full_with_distances <- full_with_elo %>%
  left_join(calc_domestic, by = "game_key")

#selecting necessary varaibles for calculations and rankings
full_with_distances <- full_with_distances %>%
  rename(visit_team = visit_team.x,
         home_team = home_team.x,
         season = season.x) %>%
  select(
    game_key,
    season,
    visit_long,
    visit_lat,
    home_long,
    home_lat,
    visit_team,
    home_team,
    color_dis,
    elo1_pre,
    elo2_pre,
    elo_prob1, 
    elo_prob2) %>%
  distinct(game_key, .keep_all = TRUE)

#note: NAs for 2007-2010 in pbp
```

```{r}
mapping_travel <- function(Season, Team) {
  #obtain all of visiting team's travel games in a given season 
  mapping_team <- full_with_distances %>%
    filter(season == Season,
           visit_team == Team)
  
  #create leaflet map 
  travel_map <- mapping_team %>%
    leaflet() %>%
    addProviderTiles(providers$CartoDB.Positron) %>%
    setView(-93.65, 42.0285, zoom = 4.3) %>%
    addMarkers( ~ visit_long, ~ visit_lat) %>%
    addMarkers( ~ home_long, ~ home_lat) %>%
    addMarkers(
      lng = mapping_team$visit_long,
      lat = mapping_team$visit_lat,
      label = mapping_team$visit_team,
      labelOptions = labelOptions(noHide = T)
    )
  
  for (i in 1:nrow(mapping_team)) {
    travel_map <- travel_map %>%
      addPolylines(
        lat = c(mapping_team[i, ]$visit_lat,
                mapping_team[i, ]$home_lat),
        lng = c(mapping_team[i, ]$visit_long,
                mapping_team[i, ]$home_long),
        color = mapping_team[i, ]$color_dis,
        dashArray = mapping_team[i,]$stroke
      ) %>%
      addTiles() %>%
      addMarkers(
        lng = mapping_team[i, ]$home_long,
        lat = mapping_team[i, ]$home_lat,
        popup = paste(
          mapping_team[i, ]$home_team,
          "<br>",
          mapping_team[i, ]$visit_team,
          "Ranking:",
          round(mapping_team[i, ]$elo2_pre, digits = 0),
          "<br>",
          mapping_team[i, ]$home_team,
          "Ranking:",
          round(mapping_team[i, ]$elo1_pre, digits = 0),
          "<br>"
        ),
        options = popupOptions(closeButton = TRUE)
      )
    travel_map
  }
  
  return(travel_map)
  
}

mapping_travel("2019", "New Orleans Saints")
```

### Winning Probability Function 

Pr(A) = 1 / 10 * (-Elo Difference / 400) + 1

```{r}
win_prob <- function(Season, Team) { 
  
  #obtain data
  elo_rankings <- full_with_distances %>%
    filter(season == Season, 
           visit_team == Team) %>% 
    mutate(elo_diff = abs(elo1_pre - elo2_pre), 
           home_wp = 1/ (10 * (elo_diff/400) + 1)) %>% 
    select(season,
           home_team,
           visit_team,
           elo1_pre,
           elo2_pre,
           home_wp,
           elo_prob1,
           elo_prob2)
  
  return(elo_rankings)
}

win_prob("2019", "Seattle Seahawks")
```

