---
title: "Q1 Analysis"
author: "Elaona Lemoto"
date: "2/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library (tidyverse)
```

```{r}

games<-read.csv("data/games_Smith.csv")
pbp<-read.csv("data/pbp_Smith.csv")

```


#Creation of 2 DFs (Thursday and Non Thursday)

```{r}

#join DF
data<-games %>% 
  left_join(pbp, by="GameKey")

#Creation of DF
thurs<-data %>% 
  filter(Game_Day=="Thursday") %>% 
  mutate()

non_thurs<-data%>% 
  filter(Game_Day!="Thursday")

```

#PLots
```{r}
#Game Days
ggplot(non_thurs, aes(Game_Day))+
  geom_histogram(stat="count")

ggplot(non_thurs, aes(as.factor(Turf)))+
  geom_bar()+
  coord_flip()

ggplot(non_thurs, aes(Temperature))+
  geom_histogram()
ggplot(thurs, aes(Temperature))+
  geom_histogram()

ggplot(non_thurs, aes(TimeZone))+
  geom_histogram(stat="count")+
  coord_flip()
#Clean up time zone
#Create a binary thursday column 


#Count
count(data, Season)
count (data, Week)
```

```{r}
data <- data %>% 
  #might want to look at this in terms of game excitement
  filter(Game_Day=="Sunday" | Game_Day=="Thursday") %>% 
  mutate(is_thurs = ifelse(Game_Day == "Thursday", 1, 0))

data_2019<-data %>% 
  filter(Season==2019)

```

```{r}

#Clean strings

pbp$PlayDescription<-str_to_lower(pbp$PlayDescription)

#Playing around with counts
data_2019<-data_2019 %>% 
  mutate(PlayDescription=as.character(PlayDescription))
kicks<-str_count(data_2019$PlayDescription,"kick")
sum(kicks)
mean(kicks)

tackle<-str_count(pbp$PlayDescription,"tackle")
sum(tackle)
mean(tackle)

pass<-str_which(pbp$PlayDescription,"pass")
sum(pass)
mean(pass)

#String counts
words <- data.frame(Var2 = c("pass", "kick", "tackle", "penalty", "punts", "fumbles", "fumble", "false start", "sacked", "pass short"),bad_plays=c("pass incomplete", "interception"),
                     stringsAsFactors = FALSE)

sapply(words$Var2,function(x){length(str_which(pbp$PlayDescription, pattern = x))})
#Create Play-by-play point


plays<-data %>% 
  mutate(pass=ifelse(str_detect(PlayDescription, "pass"), 1,0), 
         pass_incm=ifelse(str_detect(PlayDescription,"pass incomplete"),1,0),
         short=ifelse(str_detect(PlayDescription,"short"),1,0),
         short_l=ifelse(str_detect(PlayDescription,"pass short left"),1,0),
         short_r=ifelse(str_detect(PlayDescription,"short right"),1,0), 
         deep=ifelse(str_detect(PlayDescription,"deep"),1,0), 
         deep_r=ifelse(str_detect(PlayDescription,"deep right"),1,0),
         deep_l=ifelse(str_detect(PlayDescription,"deep left"),1,0),
         penalty=ifelse(str_detect(PlayDescription,"penalty"),1,0),
         tackle=ifelse(str_detect(PlayDescription,"tackle"),1,0),
         punts=ifelse(str_detect(PlayDescription,"punts"),1,0),
         fumbles=ifelse(str_detect(PlayDescription,"fumbles"),1,0),
         false_start=ifelse(str_detect(PlayDescription,"false start"),1,0), 
         sacked=ifelse(str_detect(PlayDescription,"sacked"),1,0),
         interception=ifelse(str_detect(PlayDescription,"interception"),1,0),
         kick=ifelse(str_detect(PlayDescription,"kick"),1,0), 
         recover=ifelse(str_detect(PlayDescription,"recover"),1,0), 
         no_gain=ifelse(str_detect(PlayDescription,"no gain"),1,0),
         roughing= ifelse(str_detect(PlayDescription,"rough"), 1, 0), 
         run = ifelse(PlayResult>0 & !(str_detect(PlayDescription, "pass") | str_detect(PlayDescription, "kick") | str_detect(PlayDescription, "punts")), 1, 0 ),
         bad_run = ifelse(PlayResult<0 & !(str_detect(PlayDescription, "pass") | str_detect(PlayDescription, "kick") | str_detect(PlayDescription, "punts")), 1, 0 ),
         bad_tackle = ifelse(PlayResult<0 & (str_detect(PlayDescription, "tackle") | str_detect(PlayDescription, "tackles")), 1, 0))


passes<-plays %>% 
  group_by(GameKey,PossessionTeam, Season, Home_Team, Visit_Team, is_thurs) %>% 
  summarize(total_short =sum(short),
            total_short_l = sum(short_l), 
            total_shortr= sum(short_r), 
            total_deep =sum(deep), 
            total_deepr =sum(deep_r), 
            total_deepl= sum(deep_l), 
            total_incm= sum(pass_incm), 
            total_passes = sum(pass), 
            total_rough = sum(roughing), 
            total_interc = sum(interception), 
            total_fumble =sum(fumbles), 
            total_run = sum(run), 
            total_btackle=sum(bad_tackle), 
            total_badrun=sum(bad_run)) %>% 
  mutate(pass_accuracy = 1-((total_incm+total_interc+total_fumble)/total_passes), 
         total_runrun = total_run+total_btackle+total_badrun,
         bad_runs = total_badrun +total_btackle, 
         run_accuracy = 1-(bad_runs/total_runrun))
#try abnd pip by gameid and filtered for thurs 
#then filtered by non-thurs 
#Create different 





```

#Graphs

```{r}

plot_accuracy<-function(team, acr){
  team<-passes %>% 
    filter(PossessionTeam==acr)

a<-ggplot(team, aes(GameKey, run_accuracy))+
  geom_point()+
  geom_smooth(method="lm", se=FALSE)+
  labs(title =acr)+
  ylim(0, 1)



b<-ggplot(team, aes(GameKey, pass_accuracy))+
  geom_point()+
  geom_smooth(method="lm", se= FALSE)+
  labs(title =acr)+
  ylim(0,1)

print(a)
print(b)
}

plot_accuracy_hist<-function(team, acr){
  team<-passes %>% 
    filter(PossessionTeam==acr)

a<-ggplot(team, aes(run_accuracy))+
  geom_histogram()+
  labs(title =acr)



b<-ggplot(team, aes(pass_accuracy))+
  geom_histogram()+
  labs(title =acr)

print(a)
print(b)
}


plot_accuracy(pit, "PIT")
plot_accuracy(blt, "BLT")
plot_accuracy_hist(pit, "PIT")
plot_accuracy_hist(blt, "BLT")
```
