---
title: "travel_permutation"
author: "Aoi Ogawa"
date: "4/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
# importing libraries
library(datasets)
library(maps)
library(tidyr)
library(tidyverse)
library(readr)
# install.packages("geosphere")
library(geosphere)
library(dplyr)
library(sp)
library(leaflet)
library(magrittr)
library(janitor)
library(lubridate)
#  install.packages("infer")
library(infer)
# install.packages("ggridges")
library(ggridges)
library(scales)

set.seed(1234)
```

### Importing data sets
```{r, include=FALSE}
# importing data
#game data
games<-read.csv("data/games_Smith.csv")
# stadium coordinates
stadium_data_coordinates <- read.csv("stadium_data_coordinates.csv")
# visit team stadium coordinates
visit_team_data <- read.csv("visit_team_data.csv")
```

### Creating datasets
```{r,include=FALSE}
#cleaning df column names to have a common variable with games (home_team)
stadium_data_coordinates <- stadium_data_coordinates %>% 
  clean_names() %>%
  rename(Stadium = stadium) %>%
  rename(Home_Team = home_team) %>%
  rename(Season = season)

games_w_coordinates <- games %>%
  inner_join(stadium_data_coordinates)

games_w_coordinates <- games_w_coordinates %>%
  inner_join(visit_team_data)

games_w_coordinates$num <-NULL
games_w_coordinates$additional_info_location <- NULL
colnames(games_w_coordinates)[colnames(games_w_coordinates) == 'longitude'] <- 'Home_lat'
colnames(games_w_coordinates)[colnames(games_w_coordinates) == 'latitude'] <- 'Home_long'

games_w_coordinates <- games_w_coordinates[!duplicated(games_w_coordinates$GameKey), ]

remove.list <- paste(c('Wembley Stadium',"Rogers Centre","Wembley","Twickenham","Estadio Azteca","Twickenham Stadium","Azteca Stadium","Tottenham Hotspur Stadium","Tottenham Hotspur"), collapse = '|')

# creating dataset with just domestic games
domestic_games <- games_w_coordinates %>%
  filter(!grepl(remove.list, Stadium)) %>%
  mutate(is_thurs = ifelse(Game_Day == "Thursday", 1, 0)) 

domestic_games <- domestic_games[!duplicated(domestic_games$GameKey), ]

# creating dataset with just international games
international_games <- games_w_coordinates %>%
  filter(grepl(remove.list, Stadium)) %>%
  mutate(is_thurs = ifelse(Game_Day == "Thursday", 1, 0)) 

international_games <- international_games[!duplicated(international_games$GameKey), ]

```

### Calculate the travel distance
```{r}

# calculate distance

calc_domestic <- domestic_games %>% 
  rowwise() %>%
  mutate(distance_m = distCosine(c(Home_long, Home_lat),c(Visit_long, Visit_lat))) %>%
  mutate(distance_mile = distance_m*0.6214/1000)

# Adding a categorical travel distance (close, far, and very far) 

calc_domestic <- calc_domestic %>%
  mutate(distance = ifelse(distance_mile > 2000, "very far",
                           ifelse(distance_mile > 1000 && distance_mile <= 2000, "far", "close"))) %>%
  mutate(color_dis = ifelse(distance == "very far", "red",
                        ifelse(distance == "far", "orange",
                               "cyan")))

```


```{r, warning=FALSE}
# create a dataset which summarised the total travel distance on Thursday or not Thursday 

sum_distance_season <- calc_domestic %>%
  group_by(Visit_Team,Season,is_thurs) %>%
  summarise(travel_dis = sum(distance_mile))%>%
  rename(team = Visit_Team)

num_games_season_visit <- calc_domestic %>%
  group_by(Visit_Team,Season,is_thurs) %>%
  summarise(num_game_visit =n()) %>%
  rename(team = Visit_Team)


games_season_sem <- calc_domestic %>%
  group_by(Visit_Team,Season,is_thurs) %>%
  rename(team=Visit_Team)

num_games_season_home <- calc_domestic %>%
  group_by(Home_Team,Season,is_thurs) %>%
  rename(team = Home_Team)

# average travel distance per team and for each season 
distance_season <- sum_distance_season %>%
  inner_join(num_games_season_visit) %>%
  inner_join(num_games_season_home)%>%
  mutate(total_game = num_game_visit + num_game_home) %>%
  mutate(avg_travel = travel_dis/total_game)


sum_distance_all <- calc_domestic %>%
  group_by(Visit_Team,is_thurs) %>%
  summarise(travel_dis =sum(distance_mile)) %>%
  rename(Team = Visit_Team)


num_games_visit <- calc_domestic %>%
  group_by(Visit_Team,is_thurs) %>%
  summarise(num_game_visit =n()) %>%
  rename(Team = Visit_Team)

num_games_home <- calc_domestic %>%
  group_by(Home_Team,is_thurs) %>%
  summarise(num_game_home =n()) %>%
  rename(Team = Home_Team) 


distance_all <- sum_distance_all %>%
  inner_join(num_games_visit) %>%
  left_join(num_games_home)

distance_all[is.na(distance_all)] <- 0

# creating a dataset with  overall average travel distance on thursday and non-thursday for each team
distance_all<- distance_all %>%
  mutate(num_game_visit = as.numeric(num_game_visit))%>%
  mutate(total_game = num_game_visit + num_game_home) %>%
  mutate(avg_travel = travel_dis/total_game) 

# changing the thursday and non-thursday game names
distance_all <- distance_all %>%
    mutate(is_thurs = recode(is_thurs,
                         "1" = "Thursday games",
                         "0" = "Not Thursday games")) %>%
  mutate(is_thurs = as.character(is_thurs))


```

```{r}
# run a permutation test 

# mean difference thurs - not thurs
diff_distance <- distance_all %>% 
  specify(avg_travel ~ is_thurs) %>% 
  calculate("diff in means", order = c("Not Thursday games", "Thursday games"))
diff_distance


# generate samples 
null_distance <- distance_all %>%
  specify(avg_travel ~ is_thurs) %>%
  hypothesize(null = "independence") %>%
  generate(reps = 5000, type = "permute") %>%
  calculate("diff in means", order = c("Not Thursday games", "Thursday games"))



null_distance %>% 
  get_pvalue(obs_stat = diff_distance, direction = "both")


# the p-value is 0.094, which means that there’s a 9.4% chance of seeing a difference at least as large as 78.2 in a world where there’s no difference

# --> no statistically significant difference between the two 
```

### Creating a graph that shows the distribution of average travel distance for thusday and non-thursday games
```{r,message=FALSE}
ggplot(distance_all, aes(x = avg_travel, y = is_thurs, fill = is_thurs)) +
  stat_density_ridges(quantile_lines = TRUE, quantiles = 2, scale = 3, color = "white") + 
  scale_fill_manual(values = c("#E69F00", "#56B4E9"), guide = FALSE) +
  labs(x = "Average travel distance from 2007 to 2018", y = NULL, title = "Comparison of Average Travel Distahce \n Thursday games - non-Thursday games") +
  theme_minimal() +
  theme(panel.grid.minor = element_blank())
```


### Creating a graph that shows the null distribution obtained from the permutation simulation
```{r}
null_distance %>% 
  visualise() +
  shade_p_value(obs_stat = diff_distance,direction = "both") + 
  labs(x = "Difference in mean travel distance\n(Not Thursday games − Thursday games)",
       y = "Count",
       subtitle = "Red line shows observed difference in mean travel distances") +
  theme_minimal() +
  theme(panel.grid.minor = element_blank()) 
```

